name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:latest

    env:
      DEVKITPRO: /opt/devkitpro

    steps:
      - name: Install git and lz4
        run: |
          apt update
          apt install git liblz4-dev -y

      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build
        shell: bash
        run: |
          set -euo pipefail
          source /etc/profile.d/devkit-env.sh
          make -j$(nproc)

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: forge-build-${{ github.sha }}
          path: |
            subsdk.nso
            main.npdm
            data/config.ini

